apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  selector:
    matchLabels:
      app: blog
  replicas: 2
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - image: registry.wawan.pro/wawan93/blog:latest
          name: blog
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: registry.wawan.pro
---
apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  selector:
    app: blog
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blog
  annotations:  
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - wawan.pro
    secretName: blog-tls
  rules:
  - host: wawan.pro
    http:
      paths:
      - backend:
          serviceName: blog
          servicePort: 80
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: blog-tls
spec:
  secretName: blog-tls
  dnsNames:
  - wawan.pro
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
